services:
  postgres:
    image: postgres:latest
    container_name: progressor-dbv1
    environment:
      POSTGRES_DB: progressorv1
      POSTGRES_USER: progressorv1
      POSTGRES_PASSWORD: progressorv1
    ports:
      - "5432:5432"
    volumes:
      - progressor_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U progressorv1 -d progressorv1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: progressor-appv1
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/progressorv1
      SPRING_DATASOURCE_USERNAME: progressorv1
      SPRING_DATASOURCE_PASSWORD: progressorv1
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  progressor_data: